# Generated by Django 4.0.1 on 2022-01-26 12:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tin", models.CharField(max_length=30, unique=True)),
                ("company", models.CharField(max_length=55)),
                ("total_amount", models.CharField(max_length=355)),
                ("address", models.CharField(max_length=155)),
                ("document_type", models.CharField(max_length=355)),
                ("number_id", models.CharField(max_length=55)),
                ("sell_for", models.CharField(max_length=155)),
                ("parsing_start_ts", models.DateTimeField(default=None)),
                ("parsing_end_ts", models.DateTimeField(default=None)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
