# Generated by Django 4.0.1 on 2022-01-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tins', '0002_alter_tin_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='updated',
        ),
    ]
